### ISSUE TITLE
Mess with tags 

### ISSUE THREAD

**Issue by FWEugene** [MailOnline/ImageViewer#107]
tag 4.0 is different from what is on `master` branch.

**Comment by zfoltin** [comment]
What's the issue there @FWEugene?

**Comment by FWEugene** [comment]
Wrong repository/branch cloned, when installing repostory via cocoapods with tag 4.0

**Comment by ealeksandrov** [comment]
No releases for 6 months, 4.0 release is 70 commits behind from master :(
And not a single amend in CHANGELOG for 10+ latest accepted PRs :(

**Comment by RuiAAPeres** [comment]
@ealeksandrov would you be ok if we make a 5.0 release?

**Comment by ealeksandrov** [comment]
If you feel it's stable for release - that would be awesome. I can provide changelog/release notes PR for latest changes.

**Comment by RuiAAPeres** [comment]
@ealeksandrov to my knowledge it is. 

I feel it's important to give a bit of context because of the current state of affairs here. This library was created due to a necessity we had when both me, @Krisiacik and @zfoltin were working at MailOnline. On the meantime we went on our separated ways to different companies. Now the, unfortunate, thing is that none of us actually has the need of this library. Which, creates this tension where we have our day-to-day work, our own interests, our families, our hobbies and then this project. 

For me personally, it's a bit difficult to constructively contribute to this library, for a couple of reasons:

1. As I said, I don't use it, or have necessity, of something like this at my current company.
2. I was never part of its development, most work was done by @Krisiacik. I was present mostly to give my opinion on some architectural points at its inception. 
3. My interests in the iOS platform are far from the visible parts (aka UI). 

So, let's see if @Krisiacik and @zfoltin are able to shed some light about this release until Monday (1st of May). If not, I will make the release myself.

Sounds fair?

**Comment by zfoltin** [comment]
That's right. A new release is looooong overdue as well as getting the readme and changelog in order. As @RuiAAPeres says, the core contributors don't use the lib day-to-day anymore and it's hard to find time maintaining something you don't actually use. Lucky we have a dedicated community around it to help.

I'll try to make some time tomorrow to look through what happened over the past months and make a new release and push to CocoaPods. In case I fail, I trust @RuiAAPeres will make a quick release on Monday. I'm not aware of any breaking changes so a 4.1 release would make sense.

Thanks for your patience and sorry for the delay. 🚧 🚑

**Comment by ealeksandrov** [comment]
Thanks a lot for your work!

**Comment by zfoltin** [comment]
No worries. Sorry it took us so long for a new release. There is plenty in it with a lot of great contributions. Thanks for helping out! 👍
