### ISSUE TITLE
Displacement view and swipe to dismiss

### ISSUE THREAD

**Issue by ealymbaev** [MailOnline/ImageViewer#88]
Hey, first of all, great library and also being developed rapidly.

Here is a little question. I am using displacement views and if I close the gallery by tapping on close button - the gallery is closed correctly and the image is animated back to displaced view.

BUT if I close the gallery with swipe gesture - it is simply going out of the screen without returning to displaced view.

Any fix for this? Or ImageViewer does not have this feature yet?

**Comment by Krisiacik** [comment]
Hi thanks for the love :),

I will probably dissapoint you on that one.

I made a deliberate decision to not even try to do that, because of strong opininions on such a UX as such a transition looks wibbly-wobbly to me.

Also it would not be a trivial task to transition from interactive animation to animated transition that uses a nonlinear path.

**Comment by ealymbaev** [comment]
Our very first goal is to make a great UX, you are right. But iOS users are used to default applications. And if we look into default Photos app - it has such a transition.

I have been researching for image viewer libraries before I stooped at yours, and some of them offered such a transition. Maybe you could have a glance at their implementation and get some inspiration?

**Comment by Krisiacik** [comment]
It would require nontrivial amount of time to implement this...which we currently do not have really.. 
So PRs are welcome.
